apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-server-conf
  labels:
    tier: monitoring
    app: grafana
data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
