apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    tier: monitoring
    app: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'crowdfunding-services'
        metrics_path: '/actuator/prometheus'
        static_configs:
        - targets: ['project-service:8123']
          labels:
            application: 'project-service'
            group: 'crowdfunding'
        - targets: ['wallet-service:8128']
          labels:
            application: 'wallet-service'
            group: 'crowdfunding'
        - targets: ['blockchain-service-api:8124']
          labels:
            application: 'blockchain-service'
            group: 'crowdfunding'
        - targets: ['user-service-api:8125']
          labels:
            application: 'user-service'
            group: 'crowdfunding'
        - targets: ['mail-service-api:8127']
          labels:
            application: 'mail-service'
            group: 'crowdfunding'

      # - job_name: 'prometheus'
      #   static_configs:
      #   - targets: ['prometheus-service:9090']
