
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-account-role
  namespace: default
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["services", "pods", "configmaps", "secrets", "endpoints"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-account-role
subjects:
- kind: ServiceAccount
  name: service-account
  namespace: default
