apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
data:
  application.properties: |-
    spring.datasource.url=jdbc:postgresql://db:5432/user_service
    spring.datasource.username=${DB_USERNAME:user_service}
    spring.datasource.password=${DB_PASSWORD:password}
    spring.datasource.driver-class-name = org.postgresql.Driver

    spring.jpa.open-in-view = false
    spring.jpa.show-sql=false
    spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
    spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.properties.hibernate.hbm2ddl.auto = validate
    spring.jpa.hibernate.ddl-auto = update

    spring.flyway.enabled=true

    grpc.server.port=8225
    grpc.server.security.enabled=false
    grpc.client.mail-service.address=static://mail-service:8227
    grpc.client.mail-service.negotiationType=PLAINTEXT

    # Custom properties
    com.ampnet.userservice.jwt.signing-key=${JWT:RfUjXn2r5u8x/ADGKbPdSgVkYp3s6adsfasdfsafdsdsfsfsfd}
    com.ampnet.userservice.mail.confirmation-needed=false

    com.ampnet.userservice.identyum.url=https://webid.identyum.com/api/webid/generateToken
    com.ampnet.userservice.identyum.username=${IDENTYUM_USERNAME}
    com.ampnet.userservice.identyum.password=${IDENTYUM_PASSWORD}
    com.ampnet.userservice.identyum.key=${IDENTYUM_KEY}

    com.ampnet.userservice.test-user.enabled=true
